version: '3.7'

services:
  app-server:
    build:
      context: grocerystore-app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always 
    networks:
      - backend
      - frontend

  app-client:
    build:
      context: client-app # Use an image built from the specified dockerfile in the `polling-app-client` directory.
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://127.0.0.1:8080
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - app-server
    networks:
      - frontend  